import type { Metadata, Viewport } from 'next'
import './globals.css'
import { inter } from './ui/fonts'
import { Toaster } from '@/components/ui/toaster'

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport: Viewport = {
  themeColor: "#ffffff"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>{children}</div>
        <Toaster />
      </body>
    </html>
  )
}
